name: build-jupyterlite
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install JupyterLite
        run: |
          python -m pip install -U pip
          pip install "jupyterlite==0.6.4" "jupyterlite-pyodide-kernel==0.6.4"
          jupyter lite --version

      - name: Build JupyterLite site
        run: |
          jupyter lite build --contents worksheets --output-dir _site --debug
          touch _site/.nojekyll
          ls -la _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
